/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_maintab_JniString */

#ifndef _Included_com_maintab_JniString
#define _Included_com_maintab_JniString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_maintab_JniString
 * Method:    getJniStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_maintab_JniString_getJniStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
