/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_roc_example_JniExample */

#ifndef _Included_com_roc_example_JniExample
#define _Included_com_roc_example_JniExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_roc_example_JniExample
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_roc_example_JniExample_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_roc_example_JniExample
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_roc_example_JniExample_square
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
